"""add unique constrain on subscription

Revision ID: 496362df4be8
Revises: 707aa83bd42b
Create Date: 2025-12-16 04:40:23.463398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '496362df4be8'
down_revision: Union[str, Sequence[str], None] = '707aa83bd42b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_subscriber_channel', 'subscriptions', ['subscriber_id', 'channel_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_subscriber_channel', 'subscriptions', type_='unique')
    # ### end Alembic commands ###
