"""add reaction constraint

Revision ID: 5a772399f369
Revises: 4cc2fbd39a39
Create Date: 2025-12-17 02:26:10.963886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a772399f369'
down_revision: Union[str, Sequence[str], None] = '4cc2fbd39a39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_video', 'reactions', ['user_id', 'video_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_video', 'reactions', type_='unique')
    # ### end Alembic commands ###
