"""add reactions to comments

Revision ID: 66b8f7b9b021
Revises: f2aa5b63c632
Create Date: 2025-12-18 02:45:14.384727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66b8f7b9b021'
down_revision: Union[str, Sequence[str], None] = 'f2aa5b63c632'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reactions', sa.Column('comment_id', sa.Integer(), nullable=True))
    op.alter_column('reactions', 'video_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('uq_user_video'), 'reactions', type_='unique')
    op.create_index('uq_reaction_user_comment', 'reactions', ['user_id', 'comment_id'], unique=True, postgresql_where=sa.text('video_id IS NULL'))
    op.create_index('uq_reaction_user_video', 'reactions', ['user_id', 'video_id'], unique=True, postgresql_where=sa.text('comment_id IS NULL'))
    op.create_foreign_key(None, 'reactions', 'comments', ['comment_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reactions', type_='foreignkey')
    op.drop_index('uq_reaction_user_video', table_name='reactions', postgresql_where=sa.text('comment_id IS NULL'))
    op.drop_index('uq_reaction_user_comment', table_name='reactions', postgresql_where=sa.text('video_id IS NULL'))
    op.create_unique_constraint(op.f('uq_user_video'), 'reactions', ['user_id', 'video_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('reactions', 'video_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('reactions', 'comment_id')
    # ### end Alembic commands ###
