"""add thumbnail_key

Revision ID: 794d96e4d429
Revises: fa018c7165ec
Create Date: 2025-12-15 01:59:14.930969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '794d96e4d429'
down_revision: Union[str, Sequence[str], None] = 'fa018c7165ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('thumbnail_key', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'thumbnail_key')
    # ### end Alembic commands ###
