"""fix constraints

Revision ID: ab7437bf21e0
Revises: 66b8f7b9b021
Create Date: 2025-12-18 02:59:03.076529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab7437bf21e0'
down_revision: Union[str, Sequence[str], None] = '66b8f7b9b021'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_reaction_user_comment'), table_name='reactions', postgresql_where='(video_id IS NULL)')
    op.drop_index(op.f('uq_reaction_user_video'), table_name='reactions', postgresql_where='(comment_id IS NULL)')
    op.create_check_constraint('check_video_or_parent_not_null', 'comments', '(video_id IS NULL) != (parent_id IS NULL)')
    op.create_check_constraint('check_video_or_comment_not_null', 'reactions', '(video_id IS NULL) != (comment_id IS NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_reaction_user_video'), 'reactions', ['user_id', 'video_id'], unique=True, postgresql_where='(comment_id IS NULL)')
    op.create_index(op.f('uq_reaction_user_comment'), 'reactions', ['user_id', 'comment_id'], unique=True, postgresql_where='(video_id IS NULL)')
    op.drop_constraint('check_video_or_parent_not_null', 'comments')
    op.drop_constraint('check_video_or_comment_not_null', 'reactions')
    # ### end Alembic commands ###
