"""empty message

Revision ID: bf76a4090204
Revises: 28f00a22d5e5
Create Date: 2026-06-10 03:24:32.983574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf76a4090204'
down_revision: Union[str, Sequence[str], None] = '28f00a22d5e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_confirmation_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('email_confirmation_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('is_confirmed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.alter_column('videos', 'thumbnail_key',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'thumbnail_key',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.drop_column('users', 'is_confirmed')
    op.drop_column('users', 'email_confirmation_sent_at')
    op.drop_column('users', 'email_confirmation_code')
    # ### end Alembic commands ###
